version: 2.1


orbs:
  python: circleci/python@1.2


jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: ls
      - run: python -m pip install --user -r requirements.txt
      - run: printf 'TOKEN=ODM5OTQ5MDkxNjkzNTI3MDUw.YJRFjA.h9ShpLZh-LESZQ4qD2qR9otsF2A\noddsKey = 811bd1b1c89e3d4ae9cb3e62cf01a468\nMONGO_CONNECT=mongodb+srv://wasiq:1234@cluster0.slwju.mongodb.net/myFirstDatabase?retryWrites=true&w=majority' > .env
      - run: cat .env  
      # - python/install-packages:
      #     pkg-manager: pip 
      #     pip-dependency-file: requirements.txt  
      - run: python3 main.py
      - run: python3 image_scraper.py
      - run: python3 api.py
      - run: python3 User.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python -m pip install --user -r requirements.txt
      - run: cd tests | python -m pytest -v

workflows:
  build_and_test:
    jobs:
      #- build
      - test
         # requires:
           # - build