version: 2.1


orbs:
  python: circleci/python@1.2


jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      
      - python/install-packages:
          pkg-manager: pip 
          pip-dependency-file: requirements.txt  
      - run: python3 main.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 -m pytest -v

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build